config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do  
   get '/users/sign_out' => 'devise/sessions#destroy'     
	end
	devise_for :models

	resources :items do
	  member do
	    patch :complete
	  end
	end
 root 'items#index'
end

app/models/item.rb
class Item < ActiveRecord::Base
	belongs_to :user
	
	def completed?
		!completed_at.blank?
	end
end

app/models/model.rb
class Model < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :items
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	before_action :find_item, only: [:show, :edit, :updtae, :destroy]
	
	def index
		if user_signed_in?
		@items = Item.where(:user_id => current_user.id).order("created_at DESC")
		end
	end
	
	def show
		
	end
	
	def new
		@item = current_user.items.build
	end
	
	def create
		@item = current_user.items.build(item_params)
		if @item.save
			redirect_to root_path
		else
			render 'new'
		end
	end
	
	def edit
	end
	
	def update
	@item = Item.find(params[:id])
		if @item.update(item_params)
			redirect_to root_path item_path(@item)
		else
			render 'edit'
		end
	end
	
	def destroy
		@item.destroy
		redirect_to action: "index"
	end
	
	def complete
		@item = Item.find(params[:id])
		@item.update_attribute(:completed_at, Time.now)
		redirect_to root_path, notice: "Item successfully completed!"
	end
	
	private
	
	def item_params
		(params.require(:item).permit(:title, :description))
	end
	def find_item
		@item = Item.find(params[:id])
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= simple_form_for @item do |f| %>
  <%= f.input :title, label: "Item" %>
  <%= f.input :description %>
  <%= f.button :submit %>
<% end %>

app/views/items/_static_landing_page.html.erb
<div class="jumbotron">
	<h1>Welcome to your Checklist</h1>
	<p>Never forget anything again!</p>
	<%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary"%>
	<%= link_to "Log In", new_user_session_path, class: "btn btn-primary" %>
	<%= %>
</div>

app/views/items/edit.html.erb
<div class="col-md-6 col-md-offset-3">
<h1>Edit Checklist Item</h1>

<%= render 'form' %>
</div>

app/views/items/index.html.erb
<% if user_signed_in? %>
	<div class="col-md-6 col-md-offset-3">
		<% @items.each do |item| %>
			<div class="index-wrapper">
				<% if item.completed? %>
					<div class="row item">
						<div class="col-md-8">
							<h2 style="opacity: 0.5;" class="item-title"><strike><%= link_to item.title, item %></strike></h2>
							<p style="opacity: 0.5;" class="item-sub-title item-desc"><%= item.description %></p>
							<p style="opacity: 0.5;" class="time-created-at item-sub-title">Completed <%= time_ago_in_words(item.completed_at) %> ago</p>
						</div>
						<div class="col-md-2">
							<p><%= link_to complete_item_path(item), method: :patch do %></p>
								<i class="fa fa-check fa-lg"></i>
							<% end %>
						</div>
						<div class="col-md-2">
							<p><%= link_to item, method: :delete, data: { confirm: "Are you sure?" } do %></p>
								<i class="fa fa-trash fa-lg"></i>
							<% end %>
						</div>	
					</div>
				<% else %>	
					<div class="row item">
						<div class="col-md-8">
							<h2 class="item-title"><%= item.title %></h2>
							<p class="item-sub-title item-desc"><%= item.description %></p>
							<p style="opacity: 0.5;" class="time-created-at item-sub-title">Created <%= time_ago_in_words(item.created_at) %> ago</p>
						</div>
						<div class="col-md-2">
							<p><%= link_to complete_item_path(item), method: :patch do %></p>
								<i class="fa fa-check fa-lg"></i>
							<% end %>
						</div>
						<div class="col-md-2">
							<p><%= link_to item, method: :delete, data: { confirm: "Are you sure?" } do %></p>
								<i class="fa fa-trash fa-lg"></i>
							<% end %>
						</div>
					</div>
				<% end %>
			</div>

		<% end %>	
	</div>
<% else %>
	<%= render 'static_landing_page' %>
<% end %>	

app/views/items/new.html.erb
<div class="col-md-6 col-md-offset-3">
<h1>New Checklist Item</h1>

<%= render 'form' %>
</div>

app/views/items/show.html.erb
<div class="col-md-6 col-md-offset-3">
	<h2><%= @item.title %></h2>
	<p><%= @item.description %></p>

	<%= link_to "Edit", edit_item_path(@item) %>
	<%= button_to "Delete", item_path(@item), :method=>:delete, :class=>:destroy %>
	<%= link_to "Back", root_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Checklist</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'default', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
</head>
<body>

	<nav class="navbar navbar-default">
		<div class="container">
			<div class="navbar-header">
				<%= link_to "Checklist", root_path, class: "navbar-brand" %>
			</div>
			<ul class="nav navbar-nav">
				<li><%= link_to "Sign Up", new_user_registration_path %></li>
				<% if current_user.present? %>
					<li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
				<% else %>
					<li><%= link_to "Log In", new_user_session_path %></li>
				<% end %>
			</ul>
			<% if user_signed_in? %>
				<%= link_to "New Item", new_item_path, class: "navbar-text navbar-link navbar-right" %>
			<% end %>
		</div>
	</nav>

	<p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <div class="container">

  	<%= yield %>

  </div>
	
</body>
</html>